Fixing e2e Testing Workflow

diff --git a/.github/workflows/ci.js.yml b/.github/workflows/ci.js.yml
--- a/.github/workflows/ci.js.yml
+++ b/.github/workflows/ci.js.yml
@@ -56,7 +56,7 @@ jobs:
       - name: "Check out Git repository"
         uses: actions/checkout@v2
       - name: "Execute smoke test on Docker"
-        run: docker-compose -f docker-compose.test.yml up --exit-code-from sut
+        run: docker-compose -f docker-compose.yml up --exit-code-from sut
   # mongodb:
   #   runs-on: ubuntu-latest
   #   steps:
@@ -85,3 +85,18 @@ jobs:
   #         username: ${{ secrets.DOCKER_USERNAME }}
   #         password: ${{ secrets.DOCKER_PASSWORD }}  
 
+  # notify-slack:
+  #   if: github.event_name == 'push' && (success() || failure())
+  #   needs:
+  #     - docker
+  #     - heroku
+  #     - lint
+  #     - e2e-in-subfolder
+  #     - smoke
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: "Slack workflow notification"
+  #       uses: Gamesight/slack-workflow-status@master
+  #       with:
+  #         repo_token: ${{ secrets.GITHUB_TOKEN }}
+  #         slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
